### ISSUE TITLE
使用rime的话，显示的和README图片不同

### ISSUE THREAD

**Issue by roachsinai** [iovxw/fcitx5-simple-theme#1]
![image](https://user-images.githubusercontent.com/9500049/54539273-cb0a8400-49d0-11e9-8a45-8f853b293934.png)

上图是使用rime的情况，不同有两处：

1. 拼音有背景颜色，影响观看
2. 候选词前面的没有了小数点

使用拼音和README图片相同。

**Comment by iovxw** [comment]
颜色修复了，但是候选词这个主题没法控制

**Comment by roachsinai** [comment]
颜色可以修复已经很不错了，感谢！
